export const closureIntakeExtensions = Object.freeze([
  {
    id: "24A", slug: "equal-column-vertical-type", title: "24A Equal-column Vertical Type",
    family: "landscape", objectType: "prototype", researchParentId: "24",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "provisional", evidenceState: "direct-review-pending",
    entrypoint: "phases/24a-equal-column-vertical/index.html", validationProfile: "vertical-equal-columns",
    summary: "保留 24 的直排 Product、upright 價格、46rem／64rem 紙面與 interaction，只將三個外部紙欄由 14:10:6 改為 1:1:1。",
    assets: { styles: ["history.css", "paper-menu-field.css", "landscape-paper.css", "vertical-landscape.css"], scripts: ["menu-fixture.js", "paper-menu-field-renderer.js", "paper-landscape-core.js", "spatial-drag.js"] },
    nextGate: "Directly review 320px, 390px and desktop; keep only if equal columns preserve dense-category reading while improving position predictability.",
    reviewDocument: "records/24a/index.html", evidencePath: null,
    sourcePr: 30, sourceCommit: "8f60a970afd7ae56b985fb77fd42556d7537b386",
  },
  {
    id: "24B", slug: "horizontal-price-labels", title: "24B Horizontal Price Labels",
    family: "landscape", objectType: "prototype", researchParentId: "24",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "provisional", evidenceState: "direct-review-pending",
    entrypoint: "phases/24b-horizontal-price-labels/index.html", validationProfile: "vertical-horizontal-prices",
    summary: "保留 24 的 14:10:6 外欄、直排 Product name 與完整 interaction，只將原價格節點改為同一 Product lane 底部的水平標籤。",
    assets: { styles: ["history.css", "paper-menu-field.css", "landscape-paper.css", "vertical-landscape.css", "horizontal-price-labels.css"], scripts: ["menu-fixture.js", "paper-menu-field-renderer.js", "paper-landscape-core.js", "spatial-drag.js"] },
    nextGate: "Directly review whether horizontal prices remain attached to their vertical Product lanes without collisions or a detached price band.",
    reviewDocument: "records/24b/index.html", evidencePath: null,
    sourcePr: 32, sourceCommit: "637967b0179bcaffc3c4e2847201161e41680796",
  },
  {
    id: "24C", slug: "fixed-type-reading-scale", title: "24C Fixed-type Reading Scale",
    family: "landscape", objectType: "prototype", researchParentId: "24",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "provisional", evidenceState: "direct-review-pending",
    entrypoint: "phases/24c-fixed-type-reading/index.html", validationProfile: "vertical-fixed-reading-type",
    summary: "保留 24 的 46rem→64rem 幾何放大、14:10:6 外欄與直排 flow，但讓 reading scale 的五個文字 token 維持 overview 尺寸。",
    assets: { styles: ["history.css", "paper-menu-field.css", "landscape-paper.css", "vertical-landscape.css", "fixed-type-reading.css"], scripts: ["menu-fixture.js", "paper-menu-field-renderer.js", "paper-landscape-core.js", "spatial-drag.js"] },
    nextGate: "Directly review whether wider reading geometry alone improves legibility; do not add compromise typography inside 24C.",
    reviewDocument: "records/24c/index.html", evidencePath: null,
    sourcePr: 37, sourceCommit: "ec55fdde84a24a9755d1768cf75d2f3b313fbd48",
  },
  {
    id: "A-M3", slug: "multiscale-return-continuity", title: "A-M3 Multi-scale Return Continuity",
    family: "relational", objectType: "correction", researchParentId: "06",
    dependsOn: [], evidenceFor: ["06"], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "browser-verified",
    entrypoint: null, validationProfile: "multiscale-return-continuity",
    summary: "記錄 category focus 前的位置與按鈕，reset 後等待 layout settle、恢復原 viewport position 與 keyboard focus，並讓深讀時 reset row 保持 sticky 可達。",
    assets: { styles: ["history.css", "multiscale-return.css"], scripts: ["menu-fixture.js", "multiscale-menu-renderer.js", "multiscale-menu-controller.js"] },
    nextGate: "Retain as a prerequisite correction; continuity success does not establish unfamiliar-reader trust or product direction.",
    reviewDocument: "records/a-m3/index.html", evidencePath: "review-assets/06-return-continuity/layout-checks.json",
    sourcePr: 36, sourceCommit: "54e4fa61f5a11d793345ee09a0b0ab3b57c8f99f",
  },
  {
    id: "A-M4", slug: "multiscale-retained-menu-truth", title: "A-M4 Retained-menu Truth",
    family: "relational", objectType: "correction", researchParentId: "06",
    dependsOn: ["A-M3"], evidenceFor: ["06"], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "browser-verified",
    entrypoint: null, validationProfile: "multiscale-retained-menu-truth",
    summary: "只改既有 scale status：overview 顯示完整菜單數量，focused state 明示其餘料理未篩除；沿用 A-M3 的 return continuity 與 sticky reset。",
    assets: { styles: ["history.css", "multiscale-return.css"], scripts: ["menu-fixture.js", "multiscale-menu-renderer.js", "multiscale-menu-controller.js"] },
    nextGate: "Run direct unfamiliar-reader trust evaluation; stop the 06 line if focus is still interpreted as filtering.",
    reviewDocument: "records/a-m4/index.html", evidencePath: "review-assets/06-retained-menu-truth/browser-checks.json",
    sourcePr: 39, sourceCommit: "69ef6f6e0247dc6362ae727adc533d23a8c45ff2",
  },
  {
    id: "26A", slug: "transition-landmarks", title: "26A Transition Landmarks",
    family: "depth", objectType: "prototype", researchParentId: "26",
    dependsOn: [], evidenceFor: ["26"], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "browser-verified",
    entrypoint: "phases/26a-transition-landmarks/index.html", validationProfile: "parallax-transition-landmarks",
    summary: "保留 26 的 camera、六個 anchors、30 個 Product positions 與 spread，只在中間 orientation 顯示最多兩個不可操作的 origin／target category landmarks。",
    assets: { styles: ["history.css", "parallax-menu-volume.css", "parallax-transition-landmarks.css"], scripts: ["menu-fixture.js", "parallax-menu-volume.js", "parallax-transition-landmarks.js"] },
    nextGate: "Preserve as a controlled mechanism; direct reader comprehension and low-end performance remain unresolved.",
    reviewDocument: "records/26a/index.html", evidencePath: "review-assets/26a/runtime-smoke.json",
    sourcePr: 16, sourceCommit: "b89e4bc8e4b21b38f95a6848adbdaf18031318f1",
  },
  {
    id: "26C", slug: "flat-recovery", title: "26C Flat Recovery",
    family: "depth", objectType: "prototype", researchParentId: "26A",
    dependsOn: ["26A"], evidenceFor: ["26"], mechanismsFrom: ["26A"], disposition: "keep-controlled", evidenceState: "browser-verified",
    entrypoint: "phases/26c-flat-recovery/index.html", validationProfile: "parallax-flat-recovery",
    summary: "在不改 orientation、endpoint、Product geometry 或 26A landmark grammar 的前提下，以 native range 直接控制既有 spread .02–1 continuum。",
    assets: { styles: ["history.css", "parallax-menu-volume.css", "parallax-transition-landmarks.css", "parallax-flat-recovery.css"], scripts: ["menu-fixture.js", "parallax-flat-recovery.js", "parallax-transition-landmarks.js"] },
    nextGate: "Preserve as a controlled recovery mechanism; do not introduce flat mode, auto-flat, a seventh endpoint or camera tracking.",
    reviewDocument: "records/26c/index.html", evidencePath: "review-assets/26c/runtime-smoke.json",
    sourcePr: 24, sourceCommit: "42e0b40c37db42af7bc7feedcd23ff33392be539",
  },
  {
    id: "25P-S1", slug: "25p-unfamiliar-reader-study", title: "25P Unfamiliar-reader Study",
    family: "depth", objectType: "study", researchParentId: "25P",
    dependsOn: ["25P-L1"], evidenceFor: ["25P", "25P-L1"], mechanismsFrom: [], disposition: "study-only", evidenceState: "participant-study-ready",
    entrypoint: "studies/25p-reader-task/index.html", validationProfile: "25p-unfamiliar-reader-study",
    summary: "以六場 2 × 3 反平衡的陌生讀者任務檢查 25P 是否能在沒有投影順序提示下完成三條件取捨；runner 不自動評分、不儲存回答，也不授權 25PA。",
    assets: { styles: ["history.css"], scripts: [] },
    nextGate: "Execute S01–S06 and classify 25PA as eligible, still blocked, or stopped.",
    reviewDocument: "records/25p-s1/index.html", evidencePath: "review-assets/25p-reader-task/layout-report.json",
    sourcePr: 34, sourceCommit: "360c1947092363b72a545265ae3c0555e49de143",
  },
  {
    id: "ARCHIVE-V2", slug: "archive-v2-closure", title: "Archive v2 Closure Synthesis",
    family: "document", objectType: "synthesis", researchParentId: null,
    dependsOn: [], evidenceFor: ["24A", "24B", "24C", "A-M3", "A-M4", "26A", "26C", "25P-S1"], mechanismsFrom: [],
    disposition: "reference", evidenceState: "implementation-only",
    entrypoint: null, validationProfile: "archive-v2-closure",
    summary: "完成 foundation、document、horizontal、matrix-paper、Landscape Core、Landscape Ablations、Vertical Landscape、Multi-scale、Depth 與 study infrastructure 的 Archive v2 intake；只封存研究邊界，不選定產品方向。",
    assets: { styles: ["history.css"], scripts: [] },
    nextGate: "Resolve pending direct-review and participant gates before product substrate selection; new prototype creation remains frozen.",
    reviewDocument: "records/archive-v2-closure/index.html", evidencePath: null,
    sourcePr: null, sourceCommit: null,
  },
]);
