/*
 * Canonical schema-v2 intake surface.
 *
 * Existing objects continue to come from prototype-registry.js during the
 * migration. New prototypes, corrections, studies, and syntheses are added
 * here (or imported here from family modules) so browser rendering and Node
 * validation consume the same extension list.
 */
export const archiveExtensions = Object.freeze([
  {
    id: "25P-L1", slug: "25p-readable-band-labels", title: "25P Readable Band Labels",
    family: "depth", objectType: "correction", researchParentId: "25P",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "browser-verified",
    entrypoint: null, validationProfile: "25p-readable-band-labels",
    summary: "在不改變 25P 三軸投影模型的前提下，補上可讀語意分帶、固定任務與受控的 focus-card 邊界修正，作為陌生讀者研究前置條件。",
    assets: { styles: ["menu-projection-band-labels.css"], scripts: ["menu-projection-band-labels.js"] },
    nextGate: "Run the consolidated unfamiliar-reader study 25P-S1.",
    reviewDocument: "records/25p-l1/index.html", evidencePath: "review-assets/25p-band-labels/browser-report.json",
    sourcePr: 31, sourceCommit: "36bc34f50333c239be0dc9b63ca914ac98084002",
  },
  {
    id: "05A", slug: "05a-minimal-ledger-row", title: "05A Minimal Ledger Row",
    family: "document", objectType: "prototype", researchParentId: "05",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "provisional", evidenceState: "browser-verified",
    entrypoint: "phases/05a-minimal-ledger/index.html", validationProfile: "minimal-ledger",
    summary: "縮短 05 的 collapsed Product row，只保留名稱、單一 cue、價格、必要狀態與 disclosure，完整資訊留在原位 inline detail。",
    assets: { styles: ["minimal-ledger.css"], scripts: ["minimal-ledger.js"] },
    nextGate: "Compare unfamiliar-reader scanning and Product recognition directly against parent 05.",
    reviewDocument: "records/05a/index.html", evidencePath: "review-assets/05a/browser-checks.json",
    sourcePr: 17, sourceCommit: "b13526d9033cca9b55a9e8a6c77127a807907f39",
  },
  {
    id: "05B", slug: "05b-editorial-ledger-rhythm", title: "05B Editorial Ledger Rhythm",
    family: "document", objectType: "prototype", researchParentId: "05",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "provisional", evidenceState: "browser-verified",
    entrypoint: "phases/05b-editorial-rhythm/index.html", validationProfile: "editorial-ledger",
    summary: "只加強 05 的 category opener 與分類間距，保留原 Product row、欄位、內容與 inline detail 幾何。",
    assets: { styles: ["editorial-ledger.css"], scripts: ["editorial-ledger.js"] },
    nextGate: "Test whether stronger category rhythm improves orientation enough to justify added document length.",
    reviewDocument: "records/05b/index.html", evidencePath: "review-assets/05b/browser-checks.json",
    sourcePr: 22, sourceCommit: "6da8ec775e7e05067789dd86b356f1841d7d568c",
  },
  {
    id: "05C", slug: "05c-narrow-column-collapse", title: "05C Narrow Column Collapse",
    family: "document", objectType: "prototype", researchParentId: "05",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "provisional", evidenceState: "browser-verified",
    entrypoint: "phases/05c-narrow-column-collapse/index.html", validationProfile: "narrow-column-collapse",
    summary: "只在 340px 以下重排 identity、cue 與 price：名稱取得完整首列，cue 與價格共用下方 meta row；390px 與 desktop 不變。",
    assets: { styles: ["narrow-column-collapse.css"], scripts: ["narrow-column-collapse.js"] },
    nextGate: "Compare narrow-screen identity recognition and price scanning directly against parent 05.",
    reviewDocument: "records/05c/index.html", evidencePath: "review-assets/05c/browser-checks.json",
    sourcePr: 28, sourceCommit: "04f948197c7dcfb4a06480d571da76c16013794b",
  },
  {
    id: "08A", slug: "compressed-truth-cue", title: "Compressed Truth Cue",
    family: "horizontal", objectType: "prototype", researchParentId: "08",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "implementation-only",
    entrypoint: "phases/08a-compressed-truth-cue/index.html", validationProfile: "spread-truth-cue",
    summary: "聚焦分類時，壓縮 siblings 保留既有的一菜一筆密度與價格分布 marks，不改 08 幾何、鏡頭或 interaction controller。",
    assets: { styles: ["history.css", "menu-spread.css", "compressed-truth-cue.css"], scripts: ["menu-fixture.js", "menu-spread-renderer.js", "spatial-drag.js"] },
    nextGate: "Directly test whether compressed truth marks improve category and price-distribution understanding without implying readable far Product names.",
    reviewDocument: "records/08a/index.html", evidencePath: "review-assets/08a/README.md",
    sourcePr: 15, sourceCommit: "89358e1cac8d02dc9aa155c82162fb85a6e87bb5",
  },
  {
    id: "09A", slug: "direct-minimap-scrub", title: "Direct Minimap Scrub",
    family: "horizontal", objectType: "prototype", researchParentId: "09",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "implementation-only",
    entrypoint: "phases/09a-direct-minimap-scrub/index.html", validationProfile: "ribbon-direct-scrub",
    summary: "讓 09 既有 minimap viewport window 可直接拖曳與鍵盤操作，精確映射到 30 道料理位置，不新增第二個 locator 或 camera。",
    assets: { styles: ["history.css", "horizontal-ribbon.css", "direct-ribbon-scrub.css"], scripts: ["menu-fixture.js", "horizontal-ribbon-renderer.js", "spatial-drag.js", "direct-ribbon-scrub.js"] },
    nextGate: "Compare long-distance Product access and recovery cost against parent 09 while retaining the same ribbon geometry.",
    reviewDocument: "records/09a/index.html", evidencePath: "review-assets/09a/README.md",
    sourcePr: 23, sourceCommit: "4778f81b6eec8db609465a6382fc06857775d72f",
  },
  {
    id: "10A", slug: "local-fisheye", title: "Local Fisheye",
    family: "horizontal", objectType: "prototype", researchParentId: "10",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "implementation-only",
    entrypoint: "phases/10a-local-fisheye/index.html", validationProfile: "fisheye-local",
    summary: "將 10 的 Product lens 形變限制在焦點 ±2 neighbourhood，固定遠方寬度與遠方 category boundaries，避免全域 normalize 造成邊界漂移。",
    assets: { styles: ["history.css", "fisheye-ribbon.css", "local-fisheye.css"], scripts: ["menu-fixture.js", "fisheye-ribbon-renderer.js", "local-fisheye.js"] },
    nextGate: "Compare local focus continuity and far-position stability against parent 10 without treating far ticks as readable Product labels.",
    reviewDocument: "records/10a/index.html", evidencePath: "review-assets/10a/README.md",
    sourcePr: 8, sourceCommit: "576e9d3c820b8f4902edd3ebdd4351ea1e81ba3a",
  },
  {
    id: "12A", slug: "semantic-paper-field", title: "12A Semantic Paper Field",
    family: "matrix-paper", objectType: "prototype", researchParentId: "12",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "browser-verified",
    entrypoint: "phases/12a-semantic-paper-field/index.html", validationProfile: "semantic-paper-field",
    summary: "保留 12 固定 2×3 geometry、Product anchors 與 translate＋scale camera，只讓 whole-sheet、near-category 與 reading scales 顯示不同資訊層級。",
    assets: { styles: ["history.css", "paper-menu-field.css", "semantic-paper-field.css"], scripts: ["menu-fixture.js", "paper-menu-field-renderer.js", "semantic-paper-field.js"] },
    nextGate: "Run the blinded parent/child reader comparison 12A-S1 before proposing elastic geometry.",
    reviewDocument: "records/12a/index.html", evidencePath: "review-assets/12a/browser-report.json",
    sourcePr: 10, sourceCommit: "595b95e3f6a65c6acdea6b3201236a149ece8cfa",
  },
  {
    id: "12A-S1", slug: "12a-reader-comparison", title: "12A Blinded Reader Comparison",
    family: "matrix-paper", objectType: "study", researchParentId: "12A",
    dependsOn: ["12A"], evidenceFor: ["12", "12A"], mechanismsFrom: [], disposition: "study-only", evidenceState: "participant-study-ready",
    entrypoint: "studies/12a-reader-comparison/index.html", validationProfile: "12a-reader-comparison",
    summary: "以隨機順序循序呈現 parent 12 與 child 12A，檢查 whole-sheet comprehension、near-category reading、detail 與位置回憶；不儲存回答。",
    assets: { styles: ["history.css"], scripts: [] },
    nextGate: "Execute the blinded sessions and classify 12A; elastic geometry remains unauthorized until repeated space-related failures meet the protocol threshold.",
    reviewDocument: "records/12a-s1/index.html", evidencePath: "review-assets/12a-reader-comparison/README.md",
    sourcePr: 11, sourceCommit: "cb0035a728dfc058a87f3f4a64b4fa1365e537c8",
  },
  {
    id: "15A", slug: "pair-local-elastic", title: "15A Pair-local Elastic",
    family: "matrix-paper", objectType: "prototype", researchParentId: "15",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "provisional", evidenceState: "implementation-only",
    entrypoint: "phases/15a-pair-local-elastic/index.html", validationProfile: "pair-local-elastic",
    summary: "將 15 的 elasticity 限制在選定分類所在的左右 pair；其他兩列維持 1:1，且不寫入 whole-sheet columns 或 row heights。",
    assets: { styles: ["history.css", "paper-menu-field.css", "pair-local-elastic.css"], scripts: ["menu-fixture.js", "paper-menu-field-renderer.js"] },
    nextGate: "Compare local reading gain, paired-category recoverability, remote stability and pair-boundary oscillation against parent 15.",
    reviewDocument: "records/15a/index.html", evidencePath: null,
    sourcePr: 13, sourceCommit: "c242a160f263ecf24e5b120ae225b65cc06c8a6f",
  },
  {
    id: "16A", slug: "stable-weighted-drag", title: "16A Stable Weighted Drag",
    family: "matrix-paper", objectType: "prototype", researchParentId: "16",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "provisional", evidenceState: "implementation-only",
    entrypoint: "phases/16a-stable-weighted-drag/index.html", validationProfile: "stable-weighted-drag",
    summary: "保留 16 的 content weighting 與 1.8× focused geometry，只把 pointer mapping 改為固定未變形的 base-weighted regions。",
    assets: { styles: ["history.css", "weighted-elastic-paper.css"], scripts: ["menu-fixture.js", "paper-menu-field-renderer.js"] },
    nextGate: "Compare forward/reverse drag boundaries and perceived control continuity against parent 16.",
    reviewDocument: "records/16a/index.html", evidencePath: null,
    sourcePr: 19, sourceCommit: "e79327a8a21cc2e313eac679833313dfbf62c710",
  },
  {
    id: "17A", slug: "minimum-target-weighted-strip", title: "17A Minimum-target Weighted Strip",
    family: "matrix-paper", objectType: "prototype", researchParentId: "17",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "provisional", evidenceState: "implementation-only",
    entrypoint: "phases/17a-minimum-target-weighted-strip/index.html", validationProfile: "minimum-target-weighted-strip",
    summary: "保留 17 的 8:6:6:4:4:2 content weighting 與 focused 4× multiplier，僅為每個分類加入 2.5rem minimum direct-target width。",
    assets: { styles: ["history.css", "weighted-horizontal-strip.css", "minimum-target-weighted-strip.css"], scripts: ["menu-fixture.js", "paper-menu-field-renderer.js"] },
    nextGate: "Compare smallest-category targeting, focused reading capacity and whether the minimum floor distorts content proportion too far.",
    reviewDocument: "records/17a/index.html", evidencePath: null,
    sourcePr: 25, sourceCommit: "98b81d7e164a4069b2fb40cf18dc4d83260e36cf",
  },
  {
    id: "18B", slug: "semantic-landscape-overview", title: "18B Semantic Zoom",
    family: "landscape", objectType: "prototype", researchParentId: "18",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "browser-verified",
    entrypoint: "phases/18b-semantic-zoom/index.html", validationProfile: "landscape-semantic-zoom",
    summary: "保留 18 的三欄×兩分類 geometry、camera 與 interaction，只在 overview 將不可讀 Product micro-copy 換成 fixture-backed category summary、count、price range 與 density traces。",
    assets: { styles: ["history.css", "paper-menu-field.css", "landscape-paper.css", "semantic-landscape-overview.css"], scripts: ["menu-fixture.js", "paper-menu-field-renderer.js", "spatial-drag.js"] },
    nextGate: "Run unfamiliar-reader comparison of overview comprehension without combining activation or detail-placement mechanisms.",
    reviewDocument: "records/18b/index.html", evidencePath: "review-assets/18b/browser-report.json",
    sourcePr: 14, sourceCommit: "1be394890fe6150ba17d853360d06591b56a767f",
  },
  {
    id: "18C", slug: "tap-to-read-landscape", title: "18C Tap-to-Read",
    family: "landscape", objectType: "prototype", researchParentId: "18",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "browser-verified",
    entrypoint: "phases/18c-tap-to-read/index.html", validationProfile: "landscape-tap-to-read",
    summary: "保留 18 的內容表示與 geometry，只讓六個 category headers 成為 overview 的閱讀入口，並把 Product actions 移出 overview 的 pointer、tab 與 accessibility action path。",
    assets: { styles: ["history.css", "paper-menu-field.css", "landscape-paper.css", "tap-to-read-landscape.css"], scripts: ["menu-fixture.js", "paper-menu-field-renderer.js", "spatial-drag.js"] },
    nextGate: "Test first-use discovery of category-entry controls without adding semantic summaries, external tabs or inline detail.",
    reviewDocument: "records/18c/index.html", evidencePath: "review-assets/18c/browser-report.json",
    sourcePr: 21, sourceCommit: "e5ab9983e94d4a2b0a4b1433b5ae3a99ed7b7781",
  },
  {
    id: "18D", slug: "inline-detail-landscape", title: "18D Inline Detail",
    family: "landscape", objectType: "prototype", researchParentId: "18",
    dependsOn: [], evidenceFor: [], mechanismsFrom: [], disposition: "keep-controlled", evidenceState: "browser-verified",
    entrypoint: "phases/18d-inline-detail/index.html", validationProfile: "landscape-inline-detail",
    summary: "保留 18 的 overview、activation、geometry 與 camera，只將 Product detail 從跨紙面 overlay 移到 selected Product row 後方的同一 category flow。",
    assets: { styles: ["history.css", "paper-menu-field.css", "landscape-paper.css", "inline-detail-landscape.css"], scripts: ["menu-fixture.js", "paper-menu-field-renderer.js", "spatial-drag.js"] },
    nextGate: "Compare local scrolling cost against overlay occlusion without combining semantic overview or category-entry activation.",
    reviewDocument: "records/18d/index.html", evidencePath: "review-assets/18d/browser-report.json",
    sourcePr: 26, sourceCommit: "ee2ed12ffda79e583e27d473f461e293a9713d27",
  },
]);
