/*
 * Canonical schema-v2 intake surface.
 *
 * Existing objects continue to come from prototype-registry.js during the
 * migration. New prototypes, corrections, studies, and syntheses are added
 * here (or imported here from family modules) so browser rendering and Node
 * validation consume the same extension list.
 */
export const archiveExtensions = Object.freeze([
  {
    id: "25P-L1",
    slug: "25p-readable-band-labels",
    title: "25P Readable Band Labels",
    family: "depth",
    objectType: "correction",
    researchParentId: "25P",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "keep-controlled",
    evidenceState: "browser-verified",
    entrypoint: null,
    validationProfile: "25p-readable-band-labels",
    summary: "在不改變 25P 三軸投影模型的前提下，補上可讀語意分帶、固定任務與受控的 focus-card 邊界修正，作為陌生讀者研究前置條件。",
    assets: {
      styles: ["menu-projection-band-labels.css"],
      scripts: ["menu-projection-band-labels.js"],
    },
    nextGate: "Run the consolidated unfamiliar-reader study 25P-S1.",
    reviewDocument: "records/25p-l1/index.html",
    evidencePath: "review-assets/25p-band-labels/browser-report.json",
    sourcePr: 31,
    sourceCommit: "36bc34f50333c239be0dc9b63ca914ac98084002",
  },
  {
    id: "05A",
    slug: "05a-minimal-ledger-row",
    title: "05A Minimal Ledger Row",
    family: "document",
    objectType: "prototype",
    researchParentId: "05",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "provisional",
    evidenceState: "browser-verified",
    entrypoint: "phases/05a-minimal-ledger/index.html",
    validationProfile: "minimal-ledger",
    summary: "縮短 05 的 collapsed Product row，只保留名稱、單一 cue、價格、必要狀態與 disclosure，完整資訊留在原位 inline detail。",
    assets: {
      styles: ["minimal-ledger.css"],
      scripts: ["minimal-ledger.js"],
    },
    nextGate: "Compare unfamiliar-reader scanning and Product recognition directly against parent 05.",
    reviewDocument: "records/05a/index.html",
    evidencePath: "review-assets/05a/browser-checks.json",
    sourcePr: 17,
    sourceCommit: "b13526d9033cca9b55a9e8a6c77127a807907f39",
  },
  {
    id: "05B",
    slug: "05b-editorial-ledger-rhythm",
    title: "05B Editorial Ledger Rhythm",
    family: "document",
    objectType: "prototype",
    researchParentId: "05",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "provisional",
    evidenceState: "browser-verified",
    entrypoint: "phases/05b-editorial-rhythm/index.html",
    validationProfile: "editorial-ledger",
    summary: "只加強 05 的 category opener 與分類間距，保留原 Product row、欄位、內容與 inline detail 幾何。",
    assets: {
      styles: ["editorial-ledger.css"],
      scripts: ["editorial-ledger.js"],
    },
    nextGate: "Test whether stronger category rhythm improves orientation enough to justify added document length.",
    reviewDocument: "records/05b/index.html",
    evidencePath: "review-assets/05b/browser-checks.json",
    sourcePr: 22,
    sourceCommit: "6da8ec775e7e05067789dd86b356f1841d7d568c",
  },
  {
    id: "05C",
    slug: "05c-narrow-column-collapse",
    title: "05C Narrow Column Collapse",
    family: "document",
    objectType: "prototype",
    researchParentId: "05",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "provisional",
    evidenceState: "browser-verified",
    entrypoint: "phases/05c-narrow-column-collapse/index.html",
    validationProfile: "narrow-column-collapse",
    summary: "只在 340px 以下重排 identity、cue 與 price：名稱取得完整首列，cue 與價格共用下方 meta row；390px 與 desktop 不變。",
    assets: {
      styles: ["narrow-column-collapse.css"],
      scripts: ["narrow-column-collapse.js"],
    },
    nextGate: "Compare narrow-screen identity recognition and price scanning directly against parent 05.",
    reviewDocument: "records/05c/index.html",
    evidencePath: "review-assets/05c/browser-checks.json",
    sourcePr: 28,
    sourceCommit: "04f948197c7dcfb4a06480d571da76c16013794b",
  },
]);
