/*
 * Canonical schema-v2 intake surface.
 *
 * Existing objects continue to come from prototype-registry.js during the
 * migration. New prototypes, corrections, studies, and syntheses are added
 * here (or imported here from family modules) so browser rendering and Node
 * validation consume the same extension list.
 */
export const archiveExtensions = Object.freeze([
  {
    id: "25P-L1",
    slug: "25p-readable-band-labels",
    title: "25P Readable Band Labels",
    family: "depth",
    objectType: "correction",
    researchParentId: "25P",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "keep-controlled",
    evidenceState: "browser-verified",
    entrypoint: null,
    validationProfile: "25p-readable-band-labels",
    summary: "在不改變 25P 三軸投影模型的前提下，補上可讀語意分帶、固定任務與受控的 focus-card 邊界修正，作為陌生讀者研究前置條件。",
    assets: {
      styles: ["menu-projection-band-labels.css"],
      scripts: ["menu-projection-band-labels.js"],
    },
    nextGate: "Run the consolidated unfamiliar-reader study 25P-S1.",
    reviewDocument: "records/25p-l1/index.html",
    evidencePath: "review-assets/25p-band-labels/browser-report.json",
    sourcePr: 31,
    sourceCommit: "36bc34f50333c239be0dc9b63ca914ac98084002",
  },
  {
    id: "05A",
    slug: "05a-minimal-ledger-row",
    title: "05A Minimal Ledger Row",
    family: "document",
    objectType: "prototype",
    researchParentId: "05",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "provisional",
    evidenceState: "browser-verified",
    entrypoint: "phases/05a-minimal-ledger/index.html",
    validationProfile: "minimal-ledger",
    summary: "縮短 05 的 collapsed Product row，只保留名稱、單一 cue、價格、必要狀態與 disclosure，完整資訊留在原位 inline detail。",
    assets: {
      styles: ["minimal-ledger.css"],
      scripts: ["minimal-ledger.js"],
    },
    nextGate: "Compare unfamiliar-reader scanning and Product recognition directly against parent 05.",
    reviewDocument: "records/05a/index.html",
    evidencePath: "review-assets/05a/browser-checks.json",
    sourcePr: 17,
    sourceCommit: "b13526d9033cca9b55a9e8a6c77127a807907f39",
  },
  {
    id: "05B",
    slug: "05b-editorial-ledger-rhythm",
    title: "05B Editorial Ledger Rhythm",
    family: "document",
    objectType: "prototype",
    researchParentId: "05",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "provisional",
    evidenceState: "browser-verified",
    entrypoint: "phases/05b-editorial-rhythm/index.html",
    validationProfile: "editorial-ledger",
    summary: "只加強 05 的 category opener 與分類間距，保留原 Product row、欄位、內容與 inline detail 幾何。",
    assets: {
      styles: ["editorial-ledger.css"],
      scripts: ["editorial-ledger.js"],
    },
    nextGate: "Test whether stronger category rhythm improves orientation enough to justify added document length.",
    reviewDocument: "records/05b/index.html",
    evidencePath: "review-assets/05b/browser-checks.json",
    sourcePr: 22,
    sourceCommit: "6da8ec775e7e05067789dd86b356f1841d7d568c",
  },
  {
    id: "05C",
    slug: "05c-narrow-column-collapse",
    title: "05C Narrow Column Collapse",
    family: "document",
    objectType: "prototype",
    researchParentId: "05",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "provisional",
    evidenceState: "browser-verified",
    entrypoint: "phases/05c-narrow-column-collapse/index.html",
    validationProfile: "narrow-column-collapse",
    summary: "只在 340px 以下重排 identity、cue 與 price：名稱取得完整首列，cue 與價格共用下方 meta row；390px 與 desktop 不變。",
    assets: {
      styles: ["narrow-column-collapse.css"],
      scripts: ["narrow-column-collapse.js"],
    },
    nextGate: "Compare narrow-screen identity recognition and price scanning directly against parent 05.",
    reviewDocument: "records/05c/index.html",
    evidencePath: "review-assets/05c/browser-checks.json",
    sourcePr: 28,
    sourceCommit: "04f948197c7dcfb4a06480d571da76c16013794b",
  },
  {
    id: "08A",
    slug: "compressed-truth-cue",
    title: "Compressed Truth Cue",
    family: "horizontal",
    objectType: "prototype",
    researchParentId: "08",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "keep-controlled",
    evidenceState: "implementation-only",
    entrypoint: "phases/08a-compressed-truth-cue/index.html",
    validationProfile: "spread-truth-cue",
    summary: "聚焦分類時，壓縮 siblings 保留既有的一菜一筆密度與價格分布 marks，不改 08 幾何、鏡頭或 interaction controller。",
    assets: {
      styles: ["history.css", "menu-spread.css", "compressed-truth-cue.css"],
      scripts: ["menu-fixture.js", "menu-spread-renderer.js", "spatial-drag.js"],
    },
    nextGate: "Directly test whether compressed truth marks improve category and price-distribution understanding without implying readable far Product names.",
    reviewDocument: "records/08a/index.html",
    evidencePath: "review-assets/08a/README.md",
    sourcePr: 15,
    sourceCommit: "89358e1cac8d02dc9aa155c82162fb85a6e87bb5",
  },
  {
    id: "09A",
    slug: "direct-minimap-scrub",
    title: "Direct Minimap Scrub",
    family: "horizontal",
    objectType: "prototype",
    researchParentId: "09",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "keep-controlled",
    evidenceState: "implementation-only",
    entrypoint: "phases/09a-direct-minimap-scrub/index.html",
    validationProfile: "ribbon-direct-scrub",
    summary: "讓 09 既有 minimap viewport window 可直接拖曳與鍵盤操作，精確映射到 30 道料理位置，不新增第二個 locator 或 camera。",
    assets: {
      styles: ["history.css", "horizontal-ribbon.css", "direct-ribbon-scrub.css"],
      scripts: ["menu-fixture.js", "horizontal-ribbon-renderer.js", "spatial-drag.js", "direct-ribbon-scrub.js"],
    },
    nextGate: "Compare long-distance Product access and recovery cost against parent 09 while retaining the same ribbon geometry.",
    reviewDocument: "records/09a/index.html",
    evidencePath: "review-assets/09a/README.md",
    sourcePr: 23,
    sourceCommit: "4778f81b6eec8db609465a6382fc06857775d72f",
  },
  {
    id: "10A",
    slug: "local-fisheye",
    title: "Local Fisheye",
    family: "horizontal",
    objectType: "prototype",
    researchParentId: "10",
    dependsOn: [],
    evidenceFor: [],
    mechanismsFrom: [],
    disposition: "keep-controlled",
    evidenceState: "implementation-only",
    entrypoint: "phases/10a-local-fisheye/index.html",
    validationProfile: "fisheye-local",
    summary: "將 10 的 Product lens 形變限制在焦點 ±2 neighbourhood，固定遠方寬度與遠方 category boundaries，避免全域 normalize 造成邊界漂移。",
    assets: {
      styles: ["history.css", "fisheye-ribbon.css", "local-fisheye.css"],
      scripts: ["menu-fixture.js", "fisheye-ribbon-renderer.js", "local-fisheye.js"],
    },
    nextGate: "Compare local focus continuity and far-position stability against parent 10 without treating far ticks as readable Product labels.",
    reviewDocument: "records/10a/index.html",
    evidencePath: "review-assets/10a/README.md",
    sourcePr: 8,
    sourceCommit: "576e9d3c820b8f4902edd3ebdd4351ea1e81ba3a",
  },
]);
