/*
 * Research snapshot fixture only.
 * Canonical product definitions remain in data/reference-menu.ts.
 * This bounded browser fixture keeps historical HTML snapshots comparable
 * without importing the production application or creating persisted state.
 */
window.menuLensResearchMenu = Object.freeze({
  restaurant: {
    name: "潮巷小館",
    description: "以台灣家常風味、日式洋食與適合分享的熱菜組成的虛構休閒餐廳。",
    summary: "30 道料理 · 6 個分類 · NT$120–NT$560",
  },
  categories: [
    {
      id: "personal-mains",
      name: "個人主餐",
      description: "附主食或可單人完成的一份主菜。",
      summary: "定食、燉煮與植物性主餐",
      priceRange: "NT$280–NT$390",
    },
    {
      id: "rice-noodles",
      name: "飯麵類",
      description: "以飯、麵或燉飯為核心的單人主食。",
      summary: "飯、燉飯、烏龍與麵食",
      priceRange: "NT$240–NT$320",
    },
    {
      id: "shared-dishes",
      name: "分享料理",
      description: "適合多人搭配飯麵與小食一起共享。",
      summary: "烤雞、海鮮、蔬食熱菜",
      priceRange: "NT$340–NT$560",
    },
    {
      id: "small-plates",
      name: "小食",
      description: "可作為開胃菜、配菜或加點的小份料理。",
      summary: "炸物、蔬菜與加點",
      priceRange: "NT$160–NT$220",
    },
    {
      id: "drinks",
      name: "飲料",
      description: "茶、氣泡飲與奶茶。",
      summary: "茶、果香氣泡與奶茶",
      priceRange: "NT$120–NT$160",
    },
    {
      id: "desserts",
      name: "甜點",
      description: "適合餐後單獨享用的小份甜點。",
      summary: "布蕾與豆乳奶酪",
      priceRange: "NT$140–NT$150",
    },
  ],
  products: [
    {
      id: "miso-grilled-chicken-set",
      categoryId: "personal-mains",
      name: "炙烤味噌雞腿定食",
      description: "味噌醬炙烤去骨雞腿，搭配季節烤蔬菜與漬物。",
      cue: "醬香、炙烤",
      price: 320,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "主食選擇",
    },
    {
      id: "lemon-koji-salmon-set",
      categoryId: "personal-mains",
      name: "檸香鹽麴鮭魚定食",
      description: "鹽麴醃鮭魚搭配檸檬、嫩葉沙拉與烤南瓜。",
      cue: "清爽、鹽麴",
      price: 360,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "主食選擇",
    },
    {
      id: "black-garlic-beef-short-rib",
      categoryId: "personal-mains",
      name: "黑蒜胡椒牛小排",
      description: "黑蒜醬與粗粒黑胡椒收汁，搭配炒菇與薯泥。",
      cue: "濃郁、胡椒",
      price: 390,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "無",
    },
    {
      id: "basil-three-cup-mushroom-set",
      categoryId: "personal-mains",
      name: "塔香三杯杏鮑菇定食",
      description: "杏鮑菇、老薑與九層塔快炒，醬香濃但不厚重。",
      cue: "蔬食、三杯",
      price: 290,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "主食選擇",
    },
    {
      id: "sichuan-mapo-tofu-pot",
      categoryId: "personal-mains",
      name: "川味麻婆豆腐鍋",
      description: "花椒、豆瓣與嫩豆腐煨煮，附一份主食。",
      cue: "麻辣、慢煨",
      price: 280,
      availability: "sold_out",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 2, label: "較慢", source: "merchant_confirmed", confidence: "high" },
      requiredConfiguration: "主食、辣度",
    },
    {
      id: "red-wine-braised-pork-cheek",
      categoryId: "personal-mains",
      name: "紅酒番茄燉豬頰",
      description: "豬頰肉以番茄、香草與紅酒慢燉，搭配奶油薯泥。",
      cue: "慢燉、酸香",
      price: 350,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 2, label: "較慢", source: "merchant_confirmed", confidence: "high" },
      requiredConfiguration: "無",
    },
    {
      id: "herb-pork-loin-pesto",
      categoryId: "personal-mains",
      name: "青醬香草豬里肌",
      description: "煎豬里肌佐羅勒青醬，搭配番茄與炙燒櫛瓜。",
      cue: "香草、清爽",
      price: 330,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "主食選擇",
    },
    {
      id: "yuzu-teriyaki-tofu-steak",
      categoryId: "personal-mains",
      name: "柚香照燒豆腐排",
      description: "板豆腐煎至金黃，淋上柚香照燒醬並搭配時蔬。",
      cue: "蔬食、柚香",
      price: 280,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "主食選擇",
    },
    {
      id: "char-siu-onsen-egg-rice",
      categoryId: "rice-noodles",
      name: "炙燒叉燒溫泉蛋飯",
      description: "炙燒叉燒、溫泉蛋、青蔥與甜醬油鋪在熱飯上。",
      cue: "濃郁、炙燒",
      price: 260,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "無",
    },
    {
      id: "truffle-mushroom-risotto",
      categoryId: "rice-noodles",
      name: "松露野菇燉飯",
      description: "綜合野菇、帕瑪森與松露香氣收進偏濃稠的燉飯。",
      cue: "蔬食、松露",
      price: 300,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 2, label: "較慢", source: "merchant_confirmed", confidence: "high" },
      requiredConfiguration: "無",
    },
    {
      id: "mentaiko-shrimp-udon",
      categoryId: "rice-noodles",
      name: "海老明太子奶油烏龍",
      description: "蝦仁、明太子與奶油醬包裹彈牙烏龍麵。",
      cue: "奶油、海味",
      price: 320,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "麵體口感",
    },
    {
      id: "green-peppercorn-chicken-noodles",
      categoryId: "rice-noodles",
      name: "青花椒雞絲拌麵",
      description: "雞絲、青花椒油與脆黃瓜拌入細麵，香麻而清爽。",
      cue: "香麻、清爽",
      price: 250,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "merchant_confirmed", confidence: "high" },
      requiredConfiguration: "辣度、麵體口感",
    },
    {
      id: "tomato-beef-wide-noodles",
      categoryId: "rice-noodles",
      name: "番茄牛腩寬麵",
      description: "番茄牛腩湯底搭配寬麵、青菜與醃蘿蔔。",
      cue: "湯麵、慢燉",
      price: 290,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 2, label: "較慢", source: "merchant_confirmed", confidence: "high" },
      requiredConfiguration: "麵體口感",
    },
    {
      id: "plum-cold-soba",
      categoryId: "rice-noodles",
      name: "梅香冷蕎麥麵",
      description: "冷蕎麥麵搭配梅醋醬汁、海苔與小黃瓜。",
      cue: "冷麵、清爽",
      price: 240,
      availability: "available",
      portion: { value: 1, label: "一人份", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "無",
    },
    {
      id: "sansho-roast-half-chicken",
      categoryId: "shared-dishes",
      name: "山椒烤雞半隻",
      description: "半隻雞以山椒、柑橘與香草慢烤，附烤根莖蔬菜。",
      cue: "3–4 人、慢烤",
      price: 520,
      availability: "available",
      portion: { value: 3, label: "約 3–4 人", source: "merchant_confirmed", confidence: "high" },
      preparation: { value: 2, label: "較慢", source: "merchant_confirmed", confidence: "high" },
      requiredConfiguration: "無",
    },
    {
      id: "shaoxing-butter-prawns",
      categoryId: "shared-dishes",
      name: "紹興奶油蝦",
      description: "蝦仁以紹興酒、蒜末與奶油快速收汁。",
      cue: "2–3 人、濃郁",
      price: 480,
      availability: "available",
      portion: { value: 2, label: "約 2–3 人", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "無",
    },
    {
      id: "garlic-salt-pepper-soft-shell-crab",
      categoryId: "shared-dishes",
      name: "蒜酥椒鹽軟殼蟹",
      description: "整隻軟殼蟹酥炸後拌入蒜酥、蔥花與椒鹽。",
      cue: "2–3 人、酥炸",
      price: 460,
      availability: "available",
      portion: { value: 2, label: "約 2–3 人", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "merchant_confirmed", confidence: "high" },
      requiredConfiguration: "無",
    },
    {
      id: "black-bean-steamed-seabass",
      categoryId: "shared-dishes",
      name: "豆豉蒸鱸魚",
      description: "鱸魚片與豆豉、薑絲清蒸，保留魚肉水分。",
      cue: "2–3 人、清蒸",
      price: 560,
      availability: "available",
      portion: { value: 2, label: "約 2–3 人", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "無",
    },
    {
      id: "kung-pao-king-oyster-mushroom",
      categoryId: "shared-dishes",
      name: "宮保杏鮑菇",
      description: "杏鮑菇、乾辣椒與花生快炒，帶甜鹹辣味。",
      cue: "蔬食、香辣",
      price: 340,
      availability: "available",
      portion: { value: 2, label: "約 2–3 人", source: "merchant_confirmed", confidence: "low" },
      preparation: { value: 1, label: "一般", source: "category_default", confidence: "medium" },
      requiredConfiguration: "辣度",
    },
    {
      id: "seasonal-vegetable-tofu-pot",
      categoryId: "shared-dishes",
      name: "季節時蔬豆腐煲",
      description: "當季蔬菜、豆腐與菇類以清醬汁煨煮。",
      cue: "蔬食、清淡",
      price: 380,
      availability: "sold_out",
      portion: { value: 2, label: "約 2–3 人", source: "category_default", confidence: "medium" },
      preparation: null,
      requiredConfiguration: "無",
    },
    {
      id: "pickled-chili-fried-chicken",
      categoryId: "small-plates",
      name: "剝皮辣椒炸雞",
      description: "雞腿塊酥炸後拌入剝皮辣椒與九層塔。",
      cue: "香辣、炸物",
      price: 220,
      availability: "available",
      portion: { value: 0, label: "小份", source: "category_default", confidence: "medium" },
      preparation: { value: 1, label: "一般", source: "merchant_confirmed", confidence: "high" },
      requiredConfiguration: "無",
    },
    {
      id: "sesame-dragon-whisker-vegetable",
      categoryId: "small-plates",
      name: "胡麻龍鬚菜",
      description: "汆燙龍鬚菜搭配自製胡麻醬與白芝麻。",
      cue: "蔬食、清爽",
      price: 160,
      availability: "available",
      portion: { value: 0, label: "小份", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "category_default", confidence: "medium" },
      requiredConfiguration: "無",
    },
    {
      id: "seared-zucchini-miso",
      categoryId: "small-plates",
      name: "炙燒櫛瓜味噌",
      description: "厚切櫛瓜炙燒後刷上白味噌醬。",
      cue: "蔬食、炙燒",
      price: 180,
      availability: "available",
      portion: { value: 0, label: "小份", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "category_default", confidence: "medium" },
      requiredConfiguration: "無",
    },
    {
      id: "salted-egg-yolk-potato-wedges",
      categoryId: "small-plates",
      name: "金沙薯角",
      description: "炸薯角裹上鹹蛋黃與少量辣椒粉。",
      cue: "濃郁、炸物",
      price: 190,
      availability: "available",
      portion: { value: 0, label: "小份", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "category_default", confidence: "medium" },
      requiredConfiguration: "無",
    },
    {
      id: "osmanthus-oolong-cold-brew",
      categoryId: "drinks",
      name: "桂花烏龍冷泡茶",
      description: "桂花香氣與烏龍茶韻清爽收尾。",
      cue: "清爽、無奶",
      price: 120,
      availability: "available",
      portion: { value: 1, label: "一杯", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "category_default", confidence: "medium" },
      requiredConfiguration: "飲用溫度",
    },
    {
      id: "brown-sugar-lemon-soda",
      categoryId: "drinks",
      name: "黑糖檸檬氣泡飲",
      description: "黑糖糖漿、檸檬汁與氣泡水調成酸甜口感。",
      cue: "酸甜、氣泡",
      price: 140,
      availability: "available",
      portion: { value: 1, label: "一杯", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "category_default", confidence: "medium" },
      requiredConfiguration: "甜度",
    },
    {
      id: "shiso-plum-tomato-iced-tea",
      categoryId: "drinks",
      name: "紫蘇梅番茄冰茶",
      description: "紫蘇梅、番茄汁與紅茶混合，帶鹹酸果香。",
      cue: "鹹酸、果香",
      price: 150,
      availability: "available",
      portion: { value: 1, label: "一杯", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "category_default", confidence: "medium" },
      requiredConfiguration: "無",
    },
    {
      id: "sea-salt-caramel-milk-tea",
      categoryId: "drinks",
      name: "海鹽焦糖奶茶",
      description: "焦糖奶茶加上海鹽奶蓋，甜鹹濃厚。",
      cue: "甜鹹、濃厚",
      price: 160,
      availability: "available",
      portion: { value: 1, label: "一杯", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "category_default", confidence: "medium" },
      requiredConfiguration: "溫度、甜度",
    },
    {
      id: "caramel-creme-brulee",
      categoryId: "desserts",
      name: "焦糖烤布蕾",
      description: "香草蛋奶布蕾覆上現烤焦糖脆殼。",
      cue: "濃郁、脆殼",
      price: 150,
      availability: "available",
      portion: { value: 0, label: "小份", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "category_default", confidence: "medium" },
      requiredConfiguration: "可選點綴",
    },
    {
      id: "yuzu-soy-milk-panna-cotta",
      categoryId: "desserts",
      name: "柚香豆乳奶酪",
      description: "豆乳奶酪搭配柚子醬與烘烤米香。",
      cue: "蔬食、清爽",
      price: 140,
      availability: "available",
      portion: { value: 0, label: "小份", source: "category_default", confidence: "medium" },
      preparation: { value: 0, label: "較快", source: "category_default", confidence: "medium" },
      requiredConfiguration: "無",
    },
  ],
});
